version: "3.9"

services:
  jetstreamcli:
    build:
      context: ./jetstreamclient
      dockerfile: ../jetstreamclient.Dockerfile
    ports:
      - "9090:9090"
    restart: always

  my-nats:
      image: nats:latest
      ports:
        - "4222:4222" # Listening for client connections
        - "6222:6222" # Listening for route connections
        - "8222:8222" # http monitor
        - "8080:8080"
      volumes:
        - ./tmp:/container # Mounting the host directory to container
      command: -c /container/nats.conf -js # Specify the configuration file and enable jetstream //